export const GET_TOURNAMENTS_REQUEST: string = 'GET_TOURNAMENTS_REQUEST';
export const GET_TOURNAMENTS_SUCCESS: string = 'GET_TOURNAMENTS_SUCCESS';
export const GET_TOURNAMENTS_FAILURE: string = 'GET_TOURNAMENTS_FAILURE';

export const EDIT_TOURNAMENT_REQUEST: string = 'EDIT_TOURNAMENT_ REQUEST';
export const EDIT_TOURNAMENT_SUCCESS: string = 'EDIT_TOURNAMENT_SUCCESS';
export const EDIT_TOURNAMENT_FAILURE: string = 'EDIT_TOURNAMENT_FAILURE';

export const DELETE_TOURNAMENT_REQUEST: string = 'DELETE_TOURNAMENT_ REQUEST';
export const DELETE_TOURNAMENT_SUCCESS: string = 'DELETE_TOURNAMENT_SUCCESS';
export const DELETE_TOURNAMENT_FAILURE: string = 'DELETE_TOURNAMENT_FAILURE';

export const CREATE_TOURNAMENT_REQUEST: string = 'CREATE_TOURNAMENT_ REQUEST';
export const CREATE_TOURNAMENT_SUCCESS: string = 'CREATE_TOURNAMENT_SUCCESS';
export const CREATE_TOURNAMENT_FAILURE: string = 'CREATE_TOURNAMENT_FAILURE';
